image: maven:3-openjdk-16-slim

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --update-snapshots"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

before_script:
  - apt-get update -qq
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package
        
deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
    - ssh builder@proxy.mythiccraft.io -p 2222 "mkdir -p /tmp/builds/$CI_JOB_ID && exit"
    - scp -rp -o StrictHostKeyChecking=no -o Port=2222 ./target/ builder@proxy.mythiccraft.io:/tmp/builds/$CI_JOB_ID/
  only:
    - master
